### PR TITLE
Bump up spray to version 1.3.2

### PR DESCRIPTION
**Pull request by ghost**
Since spray has now released 1.3.2, let's bump up the version to use it rather than the snapshot versions.

@sclasen Do you think this is the right time to release a new version of spray-aws as well? There are several feature improvements since last spray-aws version which only the dependency on non-stable spray release stopped us from using. Maybe more users had similar worries.

### CODE REVIEW

**Comment by sclasen** [comment]
I'll merge this and push a snasphot today. have you had a chance to test this out yet? if you think it works fine we can also push a new release, let me know!

**Comment by sclasen** [comment]
@petter-fidesmo just published 0.3.6-SNAPSHOT, let me know if you think we are good for a 0.3.6 release.

**Comment by ghost** [comment]
@sclasen We are running this version in production now. Will let you know if we are having any problems. One problem is that we are only using DynamoDB, SQS and S3 integrations, so none of the others will get tested in our deployments.

**Comment by sclasen** [comment]
Thanks! that should be a decent enough test surface given the changes.  Let
me know, and I'll cut the release!

**Comment by ghost** [comment]
@sclasen We have been running the snapshot for some 25 days now and everything has been stable for us. I guess we could cut the release now.

**Pull request merged**
